Amaznooon/Amaznooon/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Amaznooon.Controllers
{
    public class AlbumController : Controller
    {
        private Classique_WebEntities db = new Classique_WebEntities();

        //
        // GET: /Album/

        public ActionResult Index(String initiale = null)
        {
            DbSqlQuery<Album> album = null;
            if (initiale != null)
                album = db.Album.SqlQuery("SELECT DISTINCT * FROM Album WHERE Album.Titre_Album LIKE '" + initiale + "%' ORDER BY Album.Titre_Album ;");
            else
                album = db.Album.SqlQuery("SELECT DISTINCT * FROM Album ORDER BY Album.Titre_Album ;");

            return View(album.ToList());
        }

        public class BinaryResult : ActionResult
        {

            public string ContentType { get; set; }
            public byte[] Data { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                HttpResponseBase response = context.HttpContext.Response;
                response.ContentType = ContentType;

                if (Data != null)
                    response.BinaryWrite(Data);
            }
        }

        public ActionResult Pochette(int id)
        {
            // On récupère la photo dans la base de donnée et on la retourne telle quelle.
            byte[] photo = db.Album.Where(i => i.Code_Album == id).Single().Pochette;

            return new BinaryResult() { ContentType = "image/jpeg", Data = photo };
        }

        public ActionResult Extrait(int id)
        {
            byte[] audio = null;
            // On récupère la photo dans la base de donnée et on la retourne telle quelle.
            try
            {
                audio = db.Enregistrement.Where(e => e.Code_Morceau == id).Single().Extrait;
            }
            catch (System.InvalidOperationException)
            {
                return null;
            }
            return new BinaryResult() { ContentType = "audio/mp3", Data = audio };
        }

        public ActionResult Album(int id = -1)
        {
            DbSqlQuery<Album> album = null;
            if (id != -1)
                album = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album JOIN Disque ON Album.Code_Album = Disque.Code_Album JOIN Composition_Disque ON Disque.Code_Disque = Composition_Disque.Code_Disque JOIN Enregistrement ON Composition_Disque.Code_Morceau = Enregistrement.Code_Morceau JOIN Interpréter ON Enregistrement.Code_Morceau = Interpréter.Code_Morceau JOIN Instrument ON Interpréter.Code_Instrument = Instrument.Code_Instrument WHERE Instrument.Code_Instrument = '" + id + "';");
            else
                album = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album;");

            return View(album.ToList());
        }

        public ActionResult AlbumGenre(int id = -1)
        {
            DbSqlQuery<Album> album = null;
            if (id != -1)
                album = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album JOIN Genre ON Album.Code_Genre = Genre.Code_Genre WHERE Album.Code_Genre = '" + id + "';");
            else
                album = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album;");

            return View(album.ToList());
        }


        //
        // GET: /Album/Details/5

        public ActionResult Details(int id = 0, int idMorceau = 0)
        {
            ViewData["IdMorceau"] = idMorceau;

            Album album = db.Album.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }

            DbSqlQuery<Enregistrement> enregistrement = db.Enregistrement.SqlQuery("SELECT Enregistrement.* FROM Enregistrement JOIN Composition_Disque ON Enregistrement.Code_Morceau = Composition_Disque.Code_Morceau JOIN Disque ON Composition_Disque.Code_Disque = Disque.Code_Disque JOIN Album ON Disque.Code_Album = Album.Code_Album WHERE Album.Code_Album = " + id + ";");
            ViewBag.Extrait = enregistrement.ToList();

            return View(album);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Amaznooon/Amaznooon/Controllers/MusicienController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Amaznooon.Controllers
{
    public class MusicienController : Controller
    {
        private Classique_WebEntities db = new Classique_WebEntities();

        public class BinaryResult : ActionResult
        {
            public string ContentType { get; set; }
            public byte[] Data { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                HttpResponseBase response = context.HttpContext.Response;
                response.ContentType = ContentType;

                if (Data != null)
                    response.BinaryWrite(Data);
            }
        }

        public ActionResult Photo(int id)
        {
            // On récupère la photo dans la base de donnée et on la retourne telle quelle.
            byte[] photo = db.Musicien.Where(m => m.Code_Musicien == id).Single().Photo;

            return new BinaryResult() { ContentType = "image/jpeg", Data = photo };
        }

        public ActionResult Interprete(String initiale = null)
        {
            DbSqlQuery<Musicien> musicien = null;
            if (initiale != null)
            {
                musicien = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* FROM Musicien JOIN Interpréter ON Musicien.Code_Musicien = Interpréter.Code_Musicien WHERE Musicien.Nom_Musicien LIKE '" + initiale + "%' ORDER BY Musicien.Nom_Musicien ;");
            }
            else
                musicien = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* FROM Musicien JOIN Interpréter ON Musicien.Code_Musicien = Interpréter.Code_Musicien ORDER BY Musicien.Nom_Musicien ;");

            return View(musicien.ToList());
        }

        public ActionResult Compositeur(String initiale = null)
        {
            DbSqlQuery<Musicien> musicien = null;
            if (initiale != null)
                musicien = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* FROM Musicien JOIN Composer ON Musicien.Code_Musicien = Composer.Code_Musicien WHERE Musicien.Nom_Musicien LIKE '" + initiale + "%' ORDER BY Musicien.Nom_Musicien ;");
            else
                musicien = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* FROM Musicien JOIN Composer ON Musicien.Code_Musicien = Composer.Code_Musicien ORDER BY Musicien.Nom_Musicien ;");

            return View(musicien.ToList());
        }

        public ActionResult ChefOrchestre(String initiale = null)
        {
            DbSqlQuery<Musicien> musicien = null;
            if (initiale != null)
                musicien = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* FROM Musicien JOIN Direction ON Musicien.Code_Musicien = Direction.Code_Musicien WHERE Musicien.Nom_Musicien LIKE '" + initiale + "%' ORDER BY Musicien.Nom_Musicien ;");
            else
                musicien = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* FROM Musicien JOIN Direction ON Musicien.Code_Musicien = Direction.Code_Musicien ORDER BY Musicien.Nom_Musicien ;");

            return View(musicien.ToList());
        }

        public ActionResult Musicien(int id = -1)
        {
            DbSqlQuery<Musicien> musicien = null;
            if (id != -1)
                musicien = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* FROM Musicien WHERE Musicien.Code_Instrument = '" + id + "' ORDER BY Musicien.Nom_Musicien ;");
            else
                musicien = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* FROM Musicien ORDER BY Musicien.Nom_Musicien ;");

            return View(musicien.ToList());
        }

        //
        // GET: /Musicien/Details/5

        public ActionResult Details(int id = 0)
        {
            Musicien musicien = db.Musicien.Find(id);
            if (musicien == null)
            {
                return HttpNotFound();
            }

            DbSqlQuery<Album> albums = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album JOIN Disque ON Album.Code_Album = Disque.Code_Album JOIN Composition_Disque ON Disque.Code_Disque = Composition_Disque.Code_Disque JOIN Enregistrement ON Composition_Disque.Code_Morceau = Enregistrement.Code_Morceau JOIN Interpréter ON Enregistrement.Code_Morceau = Interpréter.Code_Morceau JOIN Musicien ON Interpréter.Code_Musicien = Musicien.Code_Musicien WHERE Musicien.Code_Musicien = " + id + " ;");
            ViewBag.Extrait = albums.ToList();

            return View(musicien);
        }

        public ActionResult DetailsCompositeurs(int id = 0)
        {
            Musicien musicien = db.Musicien.Find(id);
            if (musicien == null)
            {
                return HttpNotFound();
            }

            DbSqlQuery<Album> albums = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album JOIN Disque ON Album.Code_Album = Disque.Code_Album JOIN Composition_Disque ON Disque.Code_Disque = Composition_Disque.Code_Disque JOIN Enregistrement ON Composition_Disque.Code_Morceau = Enregistrement.Code_Morceau JOIN Composition ON Enregistrement.Code_Composition = Composition.Code_Composition JOIN Composition_Oeuvre ON Composition.Code_Composition = Composition_Oeuvre.Code_Composition JOIN Oeuvre ON Composition_Oeuvre.Code_Oeuvre = Oeuvre.Code_Oeuvre JOIN Composer ON Oeuvre.Code_Oeuvre = Composer.Code_Oeuvre JOIN Musicien ON Composer.Code_Musicien = Musicien.Code_Musicien WHERE Musicien.Code_Musicien = " + id + ";");
            ViewBag.Extrait = albums.ToList();

            return View(musicien);
        }

        public ActionResult DetailsChef(int id = 0)
        {
            Musicien musicien = db.Musicien.Find(id);
            if (musicien == null)
            {
                return HttpNotFound();
            }

            DbSqlQuery<Album> albums = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album JOIN Disque ON Album.Code_Album = Disque.Code_Album JOIN Composition_Disque ON Disque.Code_Disque = Composition_Disque.Code_Disque JOIN Enregistrement ON Composition_Disque.Code_Morceau = Enregistrement.Code_Morceau JOIN Direction ON Enregistrement.Code_Morceau = Direction.Code_Morceau JOIN Musicien ON Direction.Code_Musicien = Musicien.Code_Musicien WHERE Musicien.Code_Musicien = " + id + ";");
            ViewBag.Extrait = albums.ToList();

            return View(musicien);
        }

        public ActionResult Epoque()
        {
            return View();
        }

        public ActionResult CompositeurParEpoque(int epoque)
        {
            int[,] tabEpoque = new int[,] { { 0, 399 }, { 400, 1499 }, { 1500, 1699 }, { 1700, 1799 }, { 1800, 1899 }, { 1900, 1999 } };

            DbSqlQuery<Musicien> musiciens = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* " +
                                                                 "FROM Musicien " +
                                                                 "JOIN Composer ON Musicien.Code_Musicien = Composer.Code_Musicien " +
                                                                 "WHERE Musicien.Année_Naissance<>Musicien.Année_Mort " +
                                                                            "AND Musicien.Année_Naissance BETWEEN '" + tabEpoque[epoque, 0] + "' AND '" + tabEpoque[epoque, 1] + "' " +
                                                                 "ORDER BY Musicien.Nom_Musicien;");

            return View(musiciens.ToList());
        }

        public ActionResult InterpreteParEpoque(int epoque)
        {
            int[,] tabEpoque = new int[,] { { 0, 1899 }, { 1900, 1909 }, { 1910, 1919 }, { 1920, 1929 }, { 1930, 1939 }, { 1940, 1949 }, { 1950, 1959 },
                                            { 1960,1969 }, { 1970, 1979 }, { 1980, 1989 }, { 1990, 2014 } };

            DbSqlQuery<Musicien> musicien = db.Musicien.SqlQuery("SELECT DISTINCT Musicien.* " +
                                                                 "FROM Musicien " +
                                                                 "JOIN Interpréter ON Musicien.Code_Musicien = Interpréter.Code_Musicien " +
                                                                 "WHERE Musicien.Année_Naissance<>Musicien.Année_Mort " +
                                                                            "AND Musicien.Année_Naissance BETWEEN '" + tabEpoque[epoque, 0] + "' AND '" + tabEpoque[epoque, 1] + "' " +
                                                                 "ORDER BY Musicien.Nom_Musicien;");

            return View(musicien.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Amaznooon/Amaznooon/Views/Musicien/ChefOrchestre.cshtml
@model IEnumerable<Amaznooon.Musicien>

@{
    ViewBag.Title = "Chef d'orchestre";
}

@section Body{
    <h2>Liste des chefs d'orchestre</h2>
    <ul class="pagination">
        @for (char c = 'A'; c <= 'Z'; c++)
        {
            <li>@Html.ActionLink(c.ToString(), "ChefOrchestre", "Musicien", new { initiale = c }, null)</li>
        }
    </ul>
    <div class="contentList">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <img src="@Url.Action("Photo", "Musicien" , new { id= item.Code_Musicien} )" width="100" height="100" />
                <br />
                @Html.ActionLink(item.Nom_Musicien + " " + item.Prénom_Musicien, "DetailsChef", new { id = item.Code_Musicien })
            </div>
        }
    </div>
}

Amaznooon/Amaznooon/Views/Musicien/Compositeur.cshtml
@model IEnumerable<Amaznooon.Musicien>

@{
    ViewBag.Title = "Compositeur";
}

@section Body{
    <h2>Liste des compositeurs</h2>
    <ul class="pagination">
        @for (char c = 'A'; c <= 'Z'; c++)
        {
            <li>@Html.ActionLink(c.ToString(), "Compositeur", "Musicien", new { initiale = c }, null)</li>
        }
    </ul>

    <div class="contentList">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <img src="@Url.Action("Photo", "Musicien" , new { id= item.Code_Musicien} )" width="100" height="100" />
                <br />
                @Html.ActionLink(item.Nom_Musicien + " " + item.Prénom_Musicien, "DetailsCompositeurs", "Musicien", new { id = item.Code_Musicien }, null)
            </div>
        }
    </div>
}

Amaznooon/Amaznooon/Views/Musicien/CompositeurParEpoque.cshtml
@model IEnumerable<Amaznooon.Musicien>
@{
    ViewBag.Title = "Compositeur";
}

@section Body{
    <h2>Compositeurs</h2>
    <div class="contentList">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <img src="@Url.Action("Photo", "Musicien" , new { id= item.Code_Musicien} )" width="100" height="100" />
                <br />
                @Html.ActionLink(item.Nom_Musicien + " " + item.Prénom_Musicien, "DetailsCompositeurs", "Musicien", new { id = item.Code_Musicien }, null)
            </div>
        }
    </div>
}

Amaznooon/Amaznooon/Views/Musicien/Details.cshtml
@model Amaznooon.Musicien

@{
    ViewBag.Title = "Details";
}

<h2>Details de l'interprête</h2>

<div class="contentList">
    <table align="center">
        <tr>
            <td rowspan="5">
                <img src="@Url.Action("Photo", "Musicien" , new { id= @Model.Code_Musicien} )" width="200" height="200" />
            </td>
        </tr>
        <tr>
            <td>@Model.Nom_Musicien</td>
        </tr>
        <tr>
            <td>@Model.Prénom_Musicien</td>
        </tr>
        <tr>
            <td>@Model.Année_Naissance <text> - </text>@Model.Année_Mort</td>
        </tr>
        <tr>
            <td>@Model.Genre.Libellé_Abrégé</td>
        </tr>
    </table>
    <fieldset>
        <legend>Albums</legend>
        @foreach (var item in ViewBag.Extrait)
        {
            <div class="col-md-3">
                <img src="@Url.Action("Pochette", "Album" , new { id= @item.Code_Album} )" width="100" height="100" />
                <br />
                @Html.ActionLink((String)@item.Titre_Album, "Details", "Album", new { id = @item.Code_Album }, null)
            </div>
        }
    </fieldset>
</div>

Amaznooon/Amaznooon/Views/Musicien/DetailsChef.cshtml
@model Amaznooon.Musicien

@{
    ViewBag.Title = "DetailsChef";
}

<h2>Details du chef d'orchestre</h2>

<div class="contentList">
    <table align="center">
        <tr>
            <td rowspan="5">
                <img src="@Url.Action("Photo", "Musicien" , new { id= @Model.Code_Musicien} )" width="200" height="200" />
            </td>
        </tr>
        <tr>
            <td>@Model.Nom_Musicien</td>
        </tr>
        <tr>
            <td>@Model.Prénom_Musicien</td>
        </tr>
        <tr>
            <td>@Model.Année_Naissance <text> - </text>@Model.Année_Mort</td>
        </tr>
        <tr>
            <td>@Model.Genre.Libellé_Abrégé</td>
        </tr>
    </table>
    <fieldset>
        <legend>Albums</legend>
        @foreach (var item in ViewBag.Extrait)
        {
            <div class="col-md-3">
                <img src="@Url.Action("Pochette", "Album" , new { id= @item.Code_Album} )" width="100" height="100" />
                <br />
                @Html.ActionLink((String)@item.Titre_Album, "Details", "Album", new { id = @item.Code_Album }, null)
            </div>
        }
    </fieldset>
</div>

Amaznooon/Amaznooon/Views/Musicien/DetailsCompositeurs.cshtml
@model Amaznooon.Musicien

@{
    ViewBag.Title = "DetailsCompositeurs";
}

<h2>Details du compositeur</h2>

<div class="contentList">
    <table align="center">
        <tr>
            <td rowspan="5">
                <img src="@Url.Action("Photo", "Musicien" , new { id= @Model.Code_Musicien} )" width="200" height="200" />
            </td>
        </tr>
        <tr>
            <td>@Model.Nom_Musicien</td>
        </tr>
        <tr>
            <td>@Model.Prénom_Musicien</td>
        </tr>
        <tr>
            <td>@Model.Année_Naissance <text> - </text>@Model.Année_Mort</td>
        </tr>
        <tr>
            <td>@Model.Genre.Libellé_Abrégé</td>
        </tr>
    </table>
    <fieldset>
        <legend>Albums</legend>
        @foreach (var item in ViewBag.Extrait)
        {
            <div class="col-md-3">
                <img src="@Url.Action("Pochette", "Album" , new { id= @item.Code_Album} )" width="100" height="100" />
                <br />
                @Html.ActionLink((String)@item.Titre_Album, "Details", "Album", new { id = @item.Code_Album }, null)
            </div>
        }
    </fieldset>
</div>

Amaznooon/Amaznooon/Views/Musicien/Epoque.cshtml
@{
    ViewBag.Title = "Epoque";
}

<h2>Epoque</h2>

<p class="lead">
    <table align="center">
        <tr>
            <th><h3 align="center">Compositeur</h3></th>
            <th><h3 align="center">Interprète</h3></th>
        </tr>
        <tr>
            <td>
<p>@Html.ActionLink("Antiquité", "CompositeurParEpoque", "Musicien", new { epoque = 0 }, new { @class = "btn btn-lg btn-default" })</p></td>
<td><p>@Html.ActionLink("Avant 1899", "InterpreteParEpoque", "Musicien", new { epoque = 0 }, new { @class = "btn btn-lg btn-default" })</p></td>
        </tr>
<tr>
    <td><p>@Html.ActionLink("Moyen-Age", "CompositeurParEpoque", "Musicien", new { epoque = 1 }, new { @class = "btn btn-lg btn-default" })</p></td>
    <td><p>@Html.ActionLink("1900-1909", "InterpreteParEpoque", "Musicien", new { epoque = 1 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
<tr>
    <td><p>@Html.ActionLink("16ème siècle", "CompositeurParEpoque", "Musicien", new { epoque = 2 }, new { @class = "btn btn-lg btn-default" })</p></td>
    <td><p>@Html.ActionLink("1910-1919", "InterpreteParEpoque", "Musicien", new { epoque = 2 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
<tr>
    <td><p>@Html.ActionLink("17ème siècle", "CompositeurParEpoque", "Musicien", new { epoque = 3 }, new { @class = "btn btn-lg btn-default" })</p></td>
    <td><p>@Html.ActionLink("1920-1929", "InterpreteParEpoque", "Musicien", new { epoque = 3 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
<tr>
    <td><p>@Html.ActionLink("18ème siècle", "CompositeurParEpoque", "Musicien", new { epoque = 4 }, new { @class = "btn btn-lg btn-default" })</p></td>
    <td><p>@Html.ActionLink("1930-1939", "InterpreteParEpoque", "Musicien", new { epoque = 4 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
<tr>
    <td><p>@Html.ActionLink("19ème siècle", "CompositeurParEpoque", "Musicien", new { epoque = 5 }, new { @class = "btn btn-lg btn-default" })</p></td>
    <td><p>@Html.ActionLink("1940-1949", "InterpreteParEpoque", "Musicien", new { epoque = 5 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
<tr>
    <td><p>@Html.ActionLink("20ème siècle", "CompositeurParEpoque", "Musicien", new { epoque = 6 }, new { @class = "btn btn-lg btn-default" })</p></td>
    <td><p>@Html.ActionLink("1950-1959", "InterpreteParEpoque", "Musicien", new { epoque = 6 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
<tr>
    <td></td>
    <td><p>@Html.ActionLink("1960-1969", "InterpreteParEpoque", "Musicien", new { epoque = 7 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
<tr>
    <td></td>
    <td><p>@Html.ActionLink("1970-1979", "InterpreteParEpoque", "Musicien", new { epoque = 8 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
<tr>
    <td></td>
    <td><p>@Html.ActionLink("1980-1989", "InterpreteParEpoque", "Musicien", new { epoque = 9 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
<tr>
    <td></td>
    <td><p>@Html.ActionLink("Après 1990", "InterpreteParEpoque", "Musicien", new { epoque = 10 }, new { @class = "btn btn-lg btn-default" })</p></td>
</tr>
    </table>
</p>

Amaznooon/Amaznooon/Views/Musicien/Interprete.cshtml
@model IEnumerable<Amaznooon.Musicien>

@{
    ViewBag.Title = "Interprete";
}

@section Body{
    <h2>Liste des musiciens</h2>
    <ul class="pagination">
        @for (char c = 'A'; c <= 'Z'; c++)
        {
            <li>@Html.ActionLink(c.ToString(), "Interprete", "Musicien", new { initiale = c }, null)</li>
        }
    </ul>

    <div class="contentList">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <img src="@Url.Action("Photo", "Musicien" , new { id= item.Code_Musicien} )" width="100" height="100" />
                <br />
                @Html.ActionLink(item.Nom_Musicien + " " + item.Prénom_Musicien, "Details", new { id = item.Code_Musicien })
            </div>
        }
    </div>
}

Amaznooon/Amaznooon/Views/Musicien/InterpreteParEpoque.cshtml
@model IEnumerable<Amaznooon.Musicien>

@{
    ViewBag.Title = "InterpreteParEpoque";
}

@section Body{
    <h2>Interpretes</h2>
    <div class="contentList">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <img src="@Url.Action("Photo", "Musicien" , new { id= item.Code_Musicien} )" width="100" height="100" />
                <br />
                @Html.ActionLink(item.Nom_Musicien + " " + item.Prénom_Musicien, "Details", "Musicien", new { id = item.Code_Musicien }, null)
            </div>
        }
    </div>
}

Amaznooon/Amaznooon/Views/Musicien/Musicien.cshtml
@model IEnumerable<Amaznooon.Musicien>

@{
    ViewBag.Title = "Interprete";
}

@section Body{
    <h2>Liste des interpretes</h2>
    <ul class="pagination">
        @for (char c = 'A'; c <= 'Z'; c++)
        {
            <li>@Html.ActionLink(c.ToString(), "Interprete", "Musicien", new { initiale = c }, null)</li>
        }
    </ul>

    <div class="contentList">
        @foreach (var item in Model)
        {
            <div class="col-md-3">
                <img src="@Url.Action("Photo", "Musicien" , new { id= item.Code_Musicien} )" width="100" height="100" />
                <br />
                @Html.ActionLink(item.Nom_Musicien + " " + item.Prénom_Musicien, "Details", new { id = item.Code_Musicien })
            </div>
        }
    </div>
}