Amaznooon/Amaznooon/Controllers/AlbumController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Amaznooon.Controllers
{
    public class AlbumController : Controller
    {
        private Classique_WebEntities db = new Classique_WebEntities();

        //
        // GET: /Album/

        public ActionResult Index(String initiale = null)
        {
            DbSqlQuery<Album> album = null;
            if (initiale != null)
                album = db.Album.SqlQuery("SELECT DISTINCT * FROM Album WHERE Album.Titre_Album LIKE '" + initiale + "%' ORDER BY Album.Titre_Album ;");
            else
                album = db.Album.SqlQuery("SELECT DISTINCT * FROM Album ORDER BY Album.Titre_Album ;");

            return View(album.ToList());
        }

        public class BinaryResult : ActionResult
        {

            public string ContentType { get; set; }
            public byte[] Data { get; set; }

            public override void ExecuteResult(ControllerContext context)
            {
                HttpResponseBase response = context.HttpContext.Response;
                response.ContentType = ContentType;

                if (Data != null)
                    response.BinaryWrite(Data);
            }
        }

        public ActionResult Pochette(int id)
        {
            // On récupère la photo dans la base de donnée et on la retourne telle quelle.
            byte[] photo = db.Album.Where(i => i.Code_Album == id).Single().Pochette;

            return new BinaryResult() { ContentType = "image/jpeg", Data = photo };
        }

        public ActionResult Extrait(int id)
        {
            byte[] audio = null;
            // On récupère la photo dans la base de donnée et on la retourne telle quelle.
            try
            {
                audio = db.Enregistrement.Where(e => e.Code_Morceau == id).Single().Extrait;
            }
            catch (System.InvalidOperationException)
            {
                return null;
            }
            return new BinaryResult() { ContentType = "audio/mp3", Data = audio };
        }

        public ActionResult Album(int id = -1)
        {
            DbSqlQuery<Album> album = null;
            if (id != -1)
                album = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album JOIN Disque ON Album.Code_Album = Disque.Code_Album JOIN Composition_Disque ON Disque.Code_Disque = Composition_Disque.Code_Disque JOIN Enregistrement ON Composition_Disque.Code_Morceau = Enregistrement.Code_Morceau JOIN Interpréter ON Enregistrement.Code_Morceau = Interpréter.Code_Morceau JOIN Instrument ON Interpréter.Code_Instrument = Instrument.Code_Instrument WHERE Instrument.Code_Instrument = '" + id + "';");
            else
                album = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album;");

            return View(album.ToList());
        }

        public ActionResult AlbumGenre(int id = -1)
        {
            DbSqlQuery<Album> album = null;
            if (id != -1)
                album = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album JOIN Genre ON Album.Code_Genre = Genre.Code_Genre WHERE Album.Code_Genre = '" + id + "';");
            else
                album = db.Album.SqlQuery("SELECT DISTINCT Album.* FROM Album;");

            return View(album.ToList());
        }


        //
        // GET: /Album/Details/5

        public ActionResult Details(int id = 0, int idMorceau = 0)
        {
            ViewData["IdMorceau"] = idMorceau;

            Album album = db.Album.Find(id);
            if (album == null)
            {
                return HttpNotFound();
            }

            DbSqlQuery<Enregistrement> enregistrement = db.Enregistrement.SqlQuery("SELECT Enregistrement.* FROM Enregistrement JOIN Composition_Disque ON Enregistrement.Code_Morceau = Composition_Disque.Code_Morceau JOIN Disque ON Composition_Disque.Code_Disque = Disque.Code_Disque JOIN Album ON Disque.Code_Album = Album.Code_Album WHERE Album.Code_Album = " + id + ";");
            ViewBag.Extrait = enregistrement.ToList();

            return View(album);
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

Amaznooon/Amaznooon/Controllers/CompteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Transactions;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using DotNetOpenAuth.AspNet;
using Microsoft.Web.WebPages.OAuth;
using WebMatrix.WebData;
using Amaznooon.Models;


namespace Amaznooon.Controllers
{
    [Authorize]
    public class CompteController : Controller
    {
        private Classique_WebEntities db = new Classique_WebEntities();

        //
        // GET: /Compte/

        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        //
        // POST: /Account/Login

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model, string returnUrl)
        {
            if (ModelState.IsValid && Login(model.UserName, model.Password))
            {
                createSession(getUser(model.UserName));
                return RedirectToLocal(returnUrl);
            }

            // Si nous sommes arrivés là, quelque chose a échoué, réafficher le formulaire
            ModelState.AddModelError("", "Le nom d'utilisateur ou mot de passe fourni est incorrect.");
            return View(model);
        }

        //
        // POST: /Account/Register

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(RegisterModel model)
        {
            ViewBag.Pays = getPays();

            if (ModelState.IsValid)
            {
                Abonné user = new Abonné();

                if (model.Login != null)
                    user.Login = model.Login.ToString();

                if (model.Password != null)
                    user.Password = model.Password.ToString();

                user.Nom_Abonné = model.Nom.ToString();

                if (model.Prénom != null)
                    user.Prénom_Abonné = model.Prénom.ToString();

                if (model.Email != null)
                    user.Email = model.Email.ToString();

                if (model.Pays != null)
                    user.Code_Pays = model.Pays;

                if (model.Ville != null)
                    user.Ville = model.Ville.ToString();

                if (model.CP != null)
                    user.Code_Postal = model.CP.ToString();

                db.Abonné.Add(user);

                try
                {
                    db.SaveChanges();
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Inscription échouée");

                    // Si nous sommes arrivés là, quelque chose a échoué, réafficher le formulaire
                    return View(model);
                }
                createSession(user);

                return RedirectToAction("Index", "Home");
            }
            // Si nous sommes arrivés là, quelque chose a échoué, réafficher le formulaire
            return View(model);
        }

        //
        // GET: /Account/Register

        [AllowAnonymous]
        public ActionResult Register()
        {
            ViewBag.Pays = getPays();

            return View();
        }

        //
        // POST: /Account/LogOff

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Logoff()
        {
            Logout();

            return RedirectToAction("Index", "Home");
        }

        //
        // POST: /Account/Manage

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Manage(RegisterModel model)
        {
            Abonné user = getUser(model.Login);

            // Si nous sommes arrivés là, quelque chose a échoué, réafficher le formulaire
            return View(user);
        }

        public ActionResult UserInformation()
        {
            Abonné user = this.Session["User"] as Abonné;

            if (user != null)
                return View(user);
            else
                return RedirectToAction("Index", "Home");
        }

        [AllowAnonymous]
        public ActionResult UpdateUserInformation()
        {
            ViewBag.Pays = getPays();

            Abonné user = this.Session["User"] as Abonné;
            ViewBag.Abonné = user;

            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult UpdateUserInformation(UpdateModel model)
        {
            Abonné user = this.Session["User"] as Abonné;
            ViewBag.Abonné = user;

            ViewBag.Pays = getPays();

            if (ModelState.IsValid)
            {
                Abonné User = db.Abonné.Find(user.Code_Abonné);

                if (model.NewPassword == null)
                    user.Password = model.OldPassword;
                else
                    user.Password = model.NewPassword;


                    if (model.Login != null)
                        User.Login = model.Login.ToString();

                    if (model.NewPassword != null)
                        User.Password = model.NewPassword.ToString();

                    if (model.Nom != null)
                        User.Nom_Abonné = model.Nom.ToString();

                    if (model.Prénom != null)
                        User.Prénom_Abonné = model.Prénom.ToString();

                    if (model.Email != null)
                        User.Email = model.Email.ToString();

                    if (model.Pays != null)
                        User.Code_Pays = model.Pays;

                    if (model.Ville != null)
                        User.Ville = model.Ville.ToString();

                    if (model.CP != null)
                        User.Code_Postal = model.CP.ToString();


                try
                {
                    db.SaveChanges();
                }
                catch (Exception)
                {
                    ModelState.AddModelError("", "Inscription échouée");

                    // Si nous sommes arrivés là, quelque chose a échoué, réafficher le formulaire
                    return View(model);
                }

                    this.Session["User"] = User;
                    this.Session["UserName"] = User.Nom_Abonné;

                    return RedirectToAction("UserInformation"); 

            }
            return View(model);          
        }


        #region Applications auxiliaires
        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }
        }

        private Abonné getUser(string login)
        {
            Abonné user = null;
            try
            {
                user = db.Abonné.Where(a => a.Login == login).Single();
            }
            catch (System.InvalidOperationException)
            {
                return null;
            }
            return user;
        }

        private bool Login(string login, string password)
        {
            Abonné user = getUser(login);
            string pass = "";

            if (user != null)
                pass = db.Abonné.Where(a => a.Login == login).Single().Password;

            return password.Equals(pass.Replace(" ", ""));
        }

        private void createSession(Abonné User)
        {
            Abonné user = User;

            List<Enregistrement> panier = new List<Enregistrement>();

            FormsAuthentication.SetAuthCookie(user.Nom_Abonné, true);

            this.Session["User"] = user;
            this.Session["UserName"] = user.Nom_Abonné;
            this.Session["Panier"] = panier;
            this.Session["NombreArticles"] = panier.Count();
        }

        private bool HasLocalAccount()
        {
            return Session["UserProfile"] != null;
        }

        private void Logout()
        {
            FormsAuthentication.SignOut();

            //Clears out Session
            this.Session.Clear();
            this.Session.Abandon();
        }

        private List<SelectListItem> getPays()
        {
            List<SelectListItem> pays = new List<SelectListItem>();

            foreach (Pays Pays in db.Pays)
            {
                SelectListItem selectList = new SelectListItem()
                {
                    Text = Pays.Nom_Pays,
                    Value = Pays.Code_Pays.ToString()
                };
                pays.Add(selectList);
            }

            return pays;
        }
        #endregion
    }
}

Amaznooon/Amaznooon/Views/Panier/DejaAcheter.cshtml
@model IEnumerable<Amaznooon.Enregistrement>

@{
    ViewBag.Title = "DejaAcheter";
}

<ul class="nav nav-tabs">
    <li role="presentation">@Html.ActionLink("Articles en cours d'achat", "Index") </li>
    <li role="presentation" class="active"><a href="#">Articles déjà achetés</a></li>
</ul>
<div class="contentList">
    <table align="center">
        <tr>
            <td colspan="4" align="center">
                <audio controls preload="none" autoplay>
                    <source src="@Url.Action("Extrait", "Album", new { id = @ViewData["IdMorceau"] })" />
                    Votre navigateur n'est pas compatible
                </audio>
            </td>
        </tr>
    </table>
    <table align="center">
            <tr>
                <th>
                    Titre
                </th>
                <th>
                    Durée
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td align="left">
                        @Html.ActionLink(@Html.Truncate(((String)item.Titre), 80), "DejaAcheter", new { id = item.Code_Morceau })
                    </td>
                    <td>
                        @item.Durée
                    </td>
                </tr>
            }
     </table>
</div>

Amaznooon/Amaznooon/Views/Panier/Index.cshtml
@model IEnumerable<Amaznooon.Enregistrement>

@{
    ViewBag.Title = "Index";
}

@section Navigation{
    <nav>
        <ul class="nav masthead-nav">
            <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
            <li>@Html.ActionLink("Catalogue", "Index", "Catalogue")</li>
            @if (Session["User"] != null)
            {
                <li class="active">@Html.ActionLink("Panier (" + this.Session["NombreArticles"].ToString() + ")", "Index", "Panier")</li>
                <li>|</li>

                <li>
                    <text>
                        Bonjour @Html.ActionLink(Session["UserName"].ToString(), "UserInformation", "Compte", null, htmlAttributes: new { title = "Gérer mon compte" }) !
                        @using (Html.BeginForm("Logoff", "Compte", FormMethod.Post, new { id = "logoutForm" }))
                        {
                            @Html.AntiForgeryToken()
                            <a href="javascript:document.getElementById('logoutForm').submit()">Se déconnecter</a>
                        }
                    </text>
                </li>
            }
            else
            {
                <li>@Html.ActionLink("Panier", "Index", "Panier")</li>
                <li>|</li>
                <li>@Html.ActionLink("Se connecter", "Login", "Compte", routeValues: null, htmlAttributes: null) </li>
                <li>@Html.ActionLink("S'inscrire", "Register", "Compte", routeValues: null, htmlAttributes: null)</li>
            }
        </ul>
    </nav>
}

<table align="center">
    <tr>
        <td>
            <ul class="nav nav-tabs">
                <li role="presentation" class="active"><a href="#">Articles en cours d'achat</a></li>
                <li role="presentation">@Html.ActionLink("Articles déjà achetés", "DejaAcheter")</li>
            </ul>
        </td>
    </tr>
</table>
@if (Model.Count() != 0)
{ 
    <table align="center">
        <tr>
            <th>
                Titre
            </th>
            <th>
                Prix
            </th>
        </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.Truncate((item.Titre.ToString()), 80)
            </td>
            <td>
                @Math.Round(Convert.ToDouble(item.Prix), 2)
            </td>
            <td>
                @Html.ActionLink("Enlever", "Delete", new { idEnregistrement = item.Code_Morceau })
            </td>
        </tr>
    }
    </table>
    @Html.ActionLink("Commander", "Acheter", "Panier", null, new { @class = "btn btn-lg btn-default" })
}
else
{
}